# Load starter seed data: NJ-area hardiness zones, 60+ plants from Rutgers Extension data, and companion relationships.
# Run with: python manage.py seed_data
from django.core.management.base import BaseCommand
from garden.models import FrostDateByZone, Plant, CompanionRelationship


class Command(BaseCommand):
    help = 'Load starter plant and zone data'

    def handle(self, *args, **options):
        self.load_zones()
        self.load_plants()
        self.load_companions()
        self.stdout.write(self.style.SUCCESS('Seed data loaded successfully!'))

    def load_zones(self):
        # Load frost dates by hardiness zone. ~15 rows covers zones 3a through 10b.
        from garden.models import FrostDateByZone

        # Average frost dates by zone (month-day format using year 2000 as base)
        # Sources: NOAA climate data, university extension services
        zones = [
            ('3a', '2000-05-15', '2000-09-15'),
            ('3b', '2000-05-10', '2000-09-20'),
            ('4a', '2000-05-06', '2000-09-25'),
            ('4b', '2000-05-01', '2000-09-30'),
            ('5a', '2000-04-28', '2000-10-05'),
            ('5b', '2000-04-22', '2000-10-10'),
            ('6a', '2000-04-21', '2000-10-17'),
            ('6b', '2000-04-15', '2000-10-21'),
            ('7a', '2000-04-10', '2000-10-28'),
            ('7b', '2000-04-05', '2000-11-01'),
            ('8a', '2000-03-25', '2000-11-07'),
            ('8b', '2000-03-15', '2000-11-15'),
            ('9a', '2000-03-01', '2000-11-25'),
            ('9b', '2000-02-15', '2000-12-10'),
            ('10a', '2000-01-31', '2000-12-20'),
            ('10b', '2000-01-15', '2000-12-31'),
        ]
        created = 0
        for zone, last_frost, first_frost in zones:
            _, was_created = FrostDateByZone.objects.update_or_create(
                zone=zone,
                defaults={'avg_last_frost': last_frost, 'avg_first_frost': first_frost}
            )
            if was_created:
                created += 1
        self.stdout.write(f'  Frost dates: {created} created, {len(zones) - created} updated')

    def load_plants(self):
        plants = [
            # TOMATOES
            {'name': 'Tomato', 'variety': 'Sun Sugar', 'plant_type': 'vegetable', 'description': 'Extremely sweet orange cherry tomato. Prolific producer, great for snacking.', 'days_to_maturity_min': 62, 'days_to_maturity_max': 65, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 24, 'seed_depth_inches': 0.25, 'min_temp_f': 50, 'start_indoors': True, 'weeks_start_indoors': 6, 'weeks_transplant': 2, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'Indeterminate — needs staking or caging. Pinch suckers for larger fruit. Very disease resistant.'},
            {'name': 'Tomato', 'variety': 'Roma', 'plant_type': 'vegetable', 'description': 'Classic paste tomato. Meaty with few seeds — great for sauce.', 'days_to_maturity_min': 75, 'days_to_maturity_max': 80, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 24, 'seed_depth_inches': 0.25, 'min_temp_f': 50, 'start_indoors': True, 'weeks_start_indoors': 6, 'weeks_transplant': 2, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'Determinate — fruits ripen around the same time. Great for canning and sauce.'},
            {'name': 'Tomato', 'variety': 'Cherokee Purple', 'plant_type': 'vegetable', 'description': 'Heirloom beefsteak with rich, complex flavor. Dark purple-pink skin.', 'days_to_maturity_min': 80, 'days_to_maturity_max': 90, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 30, 'seed_depth_inches': 0.25, 'min_temp_f': 50, 'start_indoors': True, 'weeks_start_indoors': 8, 'weeks_transplant': 2, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'Indeterminate. Benefits from consistent watering to prevent cracking. Stake well — heavy fruits.'},
            {'name': 'Tomato', 'variety': 'Better Boy', 'plant_type': 'vegetable', 'description': 'Reliable hybrid slicer. Large red fruits, heavy yields, good disease resistance.', 'days_to_maturity_min': 70, 'days_to_maturity_max': 75, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 24, 'seed_depth_inches': 0.25, 'min_temp_f': 50, 'start_indoors': True, 'weeks_start_indoors': 6, 'weeks_transplant': 2, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'Indeterminate. One of the most popular slicing tomatoes. VFN disease resistant.'},
            # PEPPERS
            {'name': 'Pepper', 'variety': 'Jalapeño', 'plant_type': 'vegetable', 'description': 'Classic hot pepper. Medium heat (2,500-8,000 SHU), thick walls, very productive.', 'days_to_maturity_min': 70, 'days_to_maturity_max': 80, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 15, 'seed_depth_inches': 0.25, 'min_temp_f': 55, 'start_indoors': True, 'weeks_start_indoors': 8, 'weeks_transplant': 2, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'Peppers love warmth. Wait until nighttime temps stay above 55°F before transplanting.'},
            {'name': 'Pepper', 'variety': 'Bell (Red)', 'plant_type': 'vegetable', 'description': 'Sweet bell pepper. Starts green, turns red when fully ripe.', 'days_to_maturity_min': 70, 'days_to_maturity_max': 85, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 15, 'seed_depth_inches': 0.25, 'min_temp_f': 55, 'start_indoors': True, 'weeks_start_indoors': 8, 'weeks_transplant': 2, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'For red peppers, leave on the plant longer after turning green. Feed with calcium to prevent blossom end rot.'},
            {'name': 'Pepper', 'variety': 'Habanero', 'plant_type': 'vegetable', 'description': 'Very hot pepper (100,000-350,000 SHU). Small, wrinkled fruits with fruity heat.', 'days_to_maturity_min': 90, 'days_to_maturity_max': 100, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 18, 'seed_depth_inches': 0.25, 'min_temp_f': 60, 'start_indoors': True, 'weeks_start_indoors': 10, 'weeks_transplant': 3, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'Needs the longest warm season of any pepper. Start early indoors. Very slow to germinate.'},
            # EGGPLANT
            {'name': 'Eggplant', 'variety': 'Black Beauty', 'plant_type': 'vegetable', 'description': 'Classic large purple-black eggplant. Glossy skin, meaty flesh.', 'days_to_maturity_min': 74, 'days_to_maturity_max': 85, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 30, 'seed_depth_inches': 0.25, 'min_temp_f': 55, 'start_indoors': True, 'weeks_start_indoors': 8, 'weeks_transplant': 2, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'Loves heat even more than tomatoes. Harvest when skin is glossy — dull skin means overripe.'},
            # MELONS
            {'name': 'Watermelon', 'variety': 'Sangria', 'plant_type': 'fruit', 'description': 'Large oval watermelon with dark green rind and sweet red flesh. 20-25 lbs.', 'days_to_maturity_min': 85, 'days_to_maturity_max': 90, 'sun_requirement': 'full_sun', 'water_needs': 'high', 'spacing_inches': 60, 'seed_depth_inches': 1.0, 'min_temp_f': 60, 'start_indoors': True, 'weeks_start_indoors': 4, 'weeks_transplant': 2, 'can_direct_sow': True, 'weeks_direct_sow': 2, 'growing_tips': 'Needs warm soil (65°F+). Give them room to sprawl. Reduce watering as fruit ripens for sweeter melons.'},
            {'name': 'Watermelon', 'variety': 'Sugar Baby', 'plant_type': 'fruit', 'description': 'Compact icebox watermelon. 8-12 lbs, perfect for small gardens.', 'days_to_maturity_min': 75, 'days_to_maturity_max': 80, 'sun_requirement': 'full_sun', 'water_needs': 'high', 'spacing_inches': 48, 'seed_depth_inches': 1.0, 'min_temp_f': 60, 'start_indoors': True, 'weeks_start_indoors': 4, 'weeks_transplant': 2, 'can_direct_sow': True, 'weeks_direct_sow': 2, 'growing_tips': 'Great for NJ gardens with shorter seasons. Thump test — sounds hollow when ripe.'},
            {'name': 'Cantaloupe', 'variety': "Hale's Best", 'plant_type': 'fruit', 'description': 'Classic muskmelon with sweet orange flesh and netted rind. 3-5 lbs.', 'days_to_maturity_min': 80, 'days_to_maturity_max': 90, 'sun_requirement': 'full_sun', 'water_needs': 'high', 'spacing_inches': 36, 'seed_depth_inches': 0.75, 'min_temp_f': 60, 'start_indoors': True, 'weeks_start_indoors': 3, 'weeks_transplant': 2, 'can_direct_sow': True, 'weeks_direct_sow': 2, 'growing_tips': 'Ripe when the stem slips off easily with slight pressure. Reduce water the last week before harvest.'},
            # CUCUMBERS
            {'name': 'Cucumber', 'variety': 'Marketmore 76', 'plant_type': 'vegetable', 'description': 'Classic slicing cucumber. Dark green, 8-9 inches. Very reliable.', 'days_to_maturity_min': 58, 'days_to_maturity_max': 65, 'sun_requirement': 'full_sun', 'water_needs': 'high', 'spacing_inches': 36, 'seed_depth_inches': 0.50, 'min_temp_f': 50, 'start_indoors': True, 'weeks_start_indoors': 3, 'weeks_transplant': 2, 'can_direct_sow': True, 'weeks_direct_sow': 1, 'growing_tips': 'Train on a trellis for straighter fruits and better air circulation. Pick frequently to keep producing.'},
            {'name': 'Cucumber', 'variety': 'Boston Pickling', 'plant_type': 'vegetable', 'description': 'Pickling cucumber. Short, blocky fruits perfect for making pickles.', 'days_to_maturity_min': 50, 'days_to_maturity_max': 58, 'sun_requirement': 'full_sun', 'water_needs': 'high', 'spacing_inches': 36, 'seed_depth_inches': 0.50, 'min_temp_f': 50, 'start_indoors': True, 'weeks_start_indoors': 3, 'weeks_transplant': 2, 'can_direct_sow': True, 'weeks_direct_sow': 1, 'growing_tips': 'Harvest small (2-4 inches) for best pickles. Gets seedy and bitter if left too long.'},
            # SQUASH
            {'name': 'Zucchini', 'variety': 'Black Beauty', 'plant_type': 'vegetable', 'description': 'Classic dark green zucchini. Extremely productive — one plant feeds a family.', 'days_to_maturity_min': 50, 'days_to_maturity_max': 60, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 24, 'seed_depth_inches': 1.0, 'min_temp_f': 50, 'start_indoors': True, 'weeks_start_indoors': 3, 'weeks_transplant': 2, 'can_direct_sow': True, 'weeks_direct_sow': 1, 'growing_tips': 'Harvest at 6-8 inches for best flavor. Check daily — they grow fast. Watch for squash vine borers.'},
            {'name': 'Yellow Squash', 'variety': 'Early Prolific Straightneck', 'plant_type': 'vegetable', 'description': 'Bright yellow summer squash. Mild flavor, very productive.', 'days_to_maturity_min': 50, 'days_to_maturity_max': 55, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 24, 'seed_depth_inches': 1.0, 'min_temp_f': 50, 'start_indoors': True, 'weeks_start_indoors': 3, 'weeks_transplant': 2, 'can_direct_sow': True, 'weeks_direct_sow': 1, 'growing_tips': 'Like zucchini, harvest young for best texture. Great sauteed, grilled, or in stir-fry.'},
            {'name': 'Butternut Squash', 'variety': 'Waltham', 'plant_type': 'vegetable', 'description': 'Sweet, nutty winter squash. Stores for months. 3-5 lbs each.', 'days_to_maturity_min': 95, 'days_to_maturity_max': 110, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 36, 'seed_depth_inches': 1.0, 'min_temp_f': 50, 'start_indoors': True, 'weeks_start_indoors': 3, 'weeks_transplant': 2, 'can_direct_sow': True, 'weeks_direct_sow': 1, 'growing_tips': 'Needs a long season. Cure in the sun for a week after harvest for best storage.'},
            {'name': 'Acorn Squash', 'variety': 'Table Queen', 'plant_type': 'vegetable', 'description': 'Dark green ribbed winter squash. Sweet, nutty flavor. About 1-2 lbs each.', 'days_to_maturity_min': 80, 'days_to_maturity_max': 90, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 36, 'seed_depth_inches': 1.0, 'min_temp_f': 50, 'start_indoors': True, 'weeks_start_indoors': 3, 'weeks_transplant': 2, 'can_direct_sow': True, 'weeks_direct_sow': 1, 'growing_tips': 'Harvest when rind is dark green and hard to dent with a fingernail. Stores 2-3 months.'},
            {'name': 'Spaghetti Squash', 'variety': 'Vegetable Spaghetti', 'plant_type': 'vegetable', 'description': 'Yellow oblong winter squash. Flesh separates into spaghetti-like strands when cooked.', 'days_to_maturity_min': 88, 'days_to_maturity_max': 100, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 36, 'seed_depth_inches': 1.0, 'min_temp_f': 50, 'start_indoors': True, 'weeks_start_indoors': 3, 'weeks_transplant': 2, 'can_direct_sow': True, 'weeks_direct_sow': 1, 'growing_tips': 'Ripe when rind turns golden yellow and sounds hollow when tapped. Low-carb pasta alternative.'},
            # PUMPKINS
            {'name': 'Pumpkin', 'variety': "Jack O'Lantern", 'plant_type': 'vegetable', 'description': 'Classic carving pumpkin. Round, orange, 10-18 lbs.', 'days_to_maturity_min': 100, 'days_to_maturity_max': 115, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 48, 'seed_depth_inches': 1.0, 'min_temp_f': 50, 'start_indoors': True, 'weeks_start_indoors': 3, 'weeks_transplant': 2, 'can_direct_sow': True, 'weeks_direct_sow': 1, 'growing_tips': 'Count backwards from Halloween — plant in early June for October harvest. Vines need lots of room.'},
            {'name': 'Pumpkin', 'variety': 'Sugar Pie', 'plant_type': 'vegetable', 'description': 'Small baking pumpkin. Sweet, smooth flesh ideal for pies. 5-8 lbs.', 'days_to_maturity_min': 100, 'days_to_maturity_max': 110, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 48, 'seed_depth_inches': 1.0, 'min_temp_f': 50, 'start_indoors': True, 'weeks_start_indoors': 3, 'weeks_transplant': 2, 'can_direct_sow': True, 'weeks_direct_sow': 1, 'growing_tips': 'Much better for eating than carving pumpkins. Roast and puree for homemade pumpkin pie.'},
            # BEANS
            {'name': 'Green Bean', 'variety': 'Blue Lake (Bush)', 'plant_type': 'vegetable', 'description': 'Classic snap bean. Heavy producer, no staking needed.', 'days_to_maturity_min': 55, 'days_to_maturity_max': 60, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 4, 'seed_depth_inches': 1.0, 'min_temp_f': 40, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': 1, 'growing_tips': 'Direct sow after frost danger. Pick frequently to keep producing. Beans fix nitrogen — great for soil.'},
            {'name': 'Green Bean', 'variety': 'Kentucky Wonder (Pole)', 'plant_type': 'vegetable', 'description': 'Heirloom pole bean. Long, tender pods with rich flavor. Climbs 6-8 feet.', 'days_to_maturity_min': 58, 'days_to_maturity_max': 65, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 6, 'seed_depth_inches': 1.0, 'min_temp_f': 40, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': 1, 'growing_tips': 'Needs a trellis, teepee, or fence to climb. Produces longer than bush types.'},
            {'name': 'Lima Bean', 'variety': 'Fordhook 242 (Bush)', 'plant_type': 'vegetable', 'description': 'Large-seeded bush lima. Creamy, buttery flavor. Heat tolerant.', 'days_to_maturity_min': 75, 'days_to_maturity_max': 85, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 4, 'seed_depth_inches': 1.0, 'min_temp_f': 50, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': 2, 'growing_tips': 'Needs warmer soil than snap beans. Wait until soil is at least 65°F.'},
            # PEAS
            {'name': 'Sugar Snap Pea', 'variety': 'Super Sugar Snap', 'plant_type': 'vegetable', 'description': 'Sweet edible-pod pea. Eat whole — pod and all. Climbs 5-6 feet.', 'days_to_maturity_min': 58, 'days_to_maturity_max': 65, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 3, 'seed_depth_inches': 1.0, 'min_temp_f': 25, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': -4, 'growing_tips': 'Cool season — plant early spring. Provide a trellis. Production stops when it gets hot.'},
            {'name': 'Snow Pea', 'variety': 'Oregon Sugar Pod', 'plant_type': 'vegetable', 'description': 'Flat edible-pod pea. Crisp and sweet, perfect for stir-fry.', 'days_to_maturity_min': 60, 'days_to_maturity_max': 70, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 3, 'seed_depth_inches': 1.0, 'min_temp_f': 25, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': -4, 'growing_tips': 'Harvest when pods are flat and peas barely visible inside. Gets starchy if left too long.'},
            # LEAFY GREENS
            {'name': 'Lettuce', 'variety': 'Buttercrunch', 'plant_type': 'vegetable', 'description': 'Buttery bibb-type lettuce. Heat tolerant, slow to bolt.', 'days_to_maturity_min': 50, 'days_to_maturity_max': 60, 'sun_requirement': 'partial_sun', 'water_needs': 'moderate', 'spacing_inches': 6, 'seed_depth_inches': 0.12, 'min_temp_f': 25, 'start_indoors': True, 'weeks_start_indoors': 5, 'weeks_transplant': -2, 'can_direct_sow': True, 'weeks_direct_sow': -4, 'growing_tips': 'Cool season crop — plant early spring or fall. Succession sow every 2 weeks.'},
            {'name': 'Lettuce', 'variety': 'Black Seeded Simpson', 'plant_type': 'vegetable', 'description': 'Light green loose-leaf lettuce. Fast growing, great for cut-and-come-again.', 'days_to_maturity_min': 45, 'days_to_maturity_max': 50, 'sun_requirement': 'partial_sun', 'water_needs': 'moderate', 'spacing_inches': 8, 'seed_depth_inches': 0.12, 'min_temp_f': 25, 'start_indoors': True, 'weeks_start_indoors': 5, 'weeks_transplant': -2, 'can_direct_sow': True, 'weeks_direct_sow': -4, 'growing_tips': 'Harvest outer leaves and the center keeps producing. One of the easiest lettuces.'},
            {'name': 'Lettuce', 'variety': 'Romaine (Parris Island Cos)', 'plant_type': 'vegetable', 'description': 'Tall, upright romaine with crisp, dark green leaves. The Caesar salad lettuce.', 'days_to_maturity_min': 65, 'days_to_maturity_max': 75, 'sun_requirement': 'partial_sun', 'water_needs': 'moderate', 'spacing_inches': 8, 'seed_depth_inches': 0.12, 'min_temp_f': 25, 'start_indoors': True, 'weeks_start_indoors': 5, 'weeks_transplant': -2, 'can_direct_sow': True, 'weeks_direct_sow': -4, 'growing_tips': 'More heat tolerant than other lettuce types. Harvest whole head or pick outer leaves.'},
            {'name': 'Spinach', 'variety': 'Bloomsdale Long Standing', 'plant_type': 'vegetable', 'description': 'Savoy-type spinach with crinkled dark green leaves. Slow to bolt.', 'days_to_maturity_min': 40, 'days_to_maturity_max': 50, 'sun_requirement': 'partial_sun', 'water_needs': 'moderate', 'spacing_inches': 4, 'seed_depth_inches': 0.50, 'min_temp_f': 20, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': -4, 'growing_tips': 'Prefers cool weather. Direct sow as soon as soil can be worked. Great for fall planting too.'},
            {'name': 'Kale', 'variety': 'Lacinato (Dinosaur)', 'plant_type': 'vegetable', 'description': 'Italian heirloom with dark blue-green textured leaves. Sweeter after frost.', 'days_to_maturity_min': 55, 'days_to_maturity_max': 65, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 15, 'seed_depth_inches': 0.50, 'min_temp_f': 10, 'start_indoors': True, 'weeks_start_indoors': 4, 'weeks_transplant': -2, 'can_direct_sow': True, 'weeks_direct_sow': -3, 'growing_tips': 'One of the hardiest greens. Harvest outer leaves and the plant keeps producing. Flavor improves after frost.'},
            {'name': 'Kale', 'variety': 'Dwarf Blue Curled Scotch', 'plant_type': 'vegetable', 'description': 'Curly kale with tightly ruffled blue-green leaves. Compact, cold-hardy.', 'days_to_maturity_min': 55, 'days_to_maturity_max': 60, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 15, 'seed_depth_inches': 0.50, 'min_temp_f': 10, 'start_indoors': True, 'weeks_start_indoors': 4, 'weeks_transplant': -2, 'can_direct_sow': True, 'weeks_direct_sow': -3, 'growing_tips': 'Classic curly kale for smoothies, chips, and salads. Massage raw leaves with olive oil to soften.'},
            {'name': 'Swiss Chard', 'variety': 'Bright Lights', 'plant_type': 'vegetable', 'description': 'Colorful chard with rainbow stems (red, orange, yellow, pink). Mild beet-like flavor.', 'days_to_maturity_min': 55, 'days_to_maturity_max': 65, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 6, 'seed_depth_inches': 0.50, 'min_temp_f': 25, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': -2, 'growing_tips': 'Cut-and-come-again — harvest outer stalks. Tolerates heat better than spinach. Beautiful in the garden.'},
            {'name': 'Collard Greens', 'variety': 'Georgia Southern', 'plant_type': 'vegetable', 'description': 'Traditional Southern green. Large, smooth blue-green leaves. Very cold hardy.', 'days_to_maturity_min': 60, 'days_to_maturity_max': 75, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 18, 'seed_depth_inches': 0.25, 'min_temp_f': 15, 'start_indoors': True, 'weeks_start_indoors': 5, 'weeks_transplant': -2, 'can_direct_sow': True, 'weeks_direct_sow': -2, 'growing_tips': 'Extremely cold hardy — survives into December in NJ. Flavor improves dramatically after frost.'},
            # BRASSICAS
            {'name': 'Broccoli', 'variety': 'Calabrese', 'plant_type': 'vegetable', 'description': 'Classic green heading broccoli. Large central head plus side shoots after harvest.', 'days_to_maturity_min': 60, 'days_to_maturity_max': 70, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 15, 'seed_depth_inches': 0.25, 'min_temp_f': 25, 'start_indoors': True, 'weeks_start_indoors': 6, 'weeks_transplant': -2, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'Harvest main head before flowers open. Side shoots produce for weeks. Great fall crop too.'},
            {'name': 'Cabbage', 'variety': 'Golden Acre', 'plant_type': 'vegetable', 'description': 'Early green cabbage. Compact 3-4 lb heads. Good for small gardens.', 'days_to_maturity_min': 60, 'days_to_maturity_max': 65, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 18, 'seed_depth_inches': 0.25, 'min_temp_f': 20, 'start_indoors': True, 'weeks_start_indoors': 6, 'weeks_transplant': -2, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'Tolerates light frost. Harvest when heads are firm. Split heads mean overripe or inconsistent watering.'},
            {'name': 'Cauliflower', 'variety': 'Snowball', 'plant_type': 'vegetable', 'description': 'White self-blanching cauliflower. Tight, smooth curds.', 'days_to_maturity_min': 60, 'days_to_maturity_max': 75, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 24, 'seed_depth_inches': 0.25, 'min_temp_f': 25, 'start_indoors': True, 'weeks_start_indoors': 6, 'weeks_transplant': -2, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'Fussiest of the brassicas. Needs consistent cool temps and moisture. Better as a fall crop in NJ.'},
            {'name': 'Brussels Sprouts', 'variety': 'Long Island Improved', 'plant_type': 'vegetable', 'description': 'Classic Brussels sprout. Firm, 1-2 inch sprouts along a tall stalk.', 'days_to_maturity_min': 90, 'days_to_maturity_max': 100, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 18, 'seed_depth_inches': 0.25, 'min_temp_f': 15, 'start_indoors': True, 'weeks_start_indoors': 6, 'weeks_transplant': -2, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'Best as a fall crop — start indoors in June for fall harvest. Flavor improves dramatically after frost.'},
            {'name': 'Kohlrabi', 'variety': 'Early White Vienna', 'plant_type': 'vegetable', 'description': 'Unusual brassica forming a bulb above ground. Mild, crisp, apple-like flavor.', 'days_to_maturity_min': 50, 'days_to_maturity_max': 60, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 4, 'seed_depth_inches': 0.25, 'min_temp_f': 25, 'start_indoors': True, 'weeks_start_indoors': 6, 'weeks_transplant': -2, 'can_direct_sow': True, 'weeks_direct_sow': -3, 'growing_tips': 'Harvest when bulb is 2-3 inches across. Gets woody if left too long. Great raw or roasted.'},
            # ROOT VEGETABLES
            {'name': 'Carrot', 'variety': 'Nantes', 'plant_type': 'vegetable', 'description': 'Sweet, cylindrical carrot. Crisp and tender — excellent for fresh eating.', 'days_to_maturity_min': 65, 'days_to_maturity_max': 75, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 3, 'seed_depth_inches': 0.25, 'min_temp_f': 20, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': -3, 'growing_tips': 'Direct sow only — carrots hate transplanting. Keep soil moist until germination (2-3 weeks). Loose soil is key.'},
            {'name': 'Carrot', 'variety': 'Danvers Half Long', 'plant_type': 'vegetable', 'description': 'Classic American carrot. Tapers to a point, 6-7 inches. Tolerates heavier soil.', 'days_to_maturity_min': 70, 'days_to_maturity_max': 80, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 3, 'seed_depth_inches': 0.25, 'min_temp_f': 20, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': -3, 'growing_tips': 'Better than Nantes types in clay-ish soil. Good for storing and cooking.'},
            {'name': 'Beet', 'variety': 'Detroit Dark Red', 'plant_type': 'vegetable', 'description': 'Classic round red beet. Sweet, smooth, deep red flesh. Greens are edible too.', 'days_to_maturity_min': 55, 'days_to_maturity_max': 65, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 3, 'seed_depth_inches': 0.50, 'min_temp_f': 25, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': -3, 'growing_tips': 'Each "seed" is actually a cluster — thin seedlings to 3 inches apart. Eat the greens too.'},
            {'name': 'Beet', 'variety': 'Chioggia', 'plant_type': 'vegetable', 'description': 'Italian heirloom with candy-stripe rings (red and white). Mild, sweet flavor.', 'days_to_maturity_min': 55, 'days_to_maturity_max': 60, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 3, 'seed_depth_inches': 0.50, 'min_temp_f': 25, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': -3, 'growing_tips': 'The rings fade with cooking — eat raw in salads to show off the pattern.'},
            {'name': 'Radish', 'variety': 'Cherry Belle', 'plant_type': 'vegetable', 'description': 'Classic round red radish. Quick to harvest, great for beginners.', 'days_to_maturity_min': 22, 'days_to_maturity_max': 28, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 1, 'seed_depth_inches': 0.50, 'min_temp_f': 25, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': -4, 'growing_tips': 'Fastest vegetable you can grow. Succession plant every 2 weeks. Gets spicy/woody if left too long.'},
            {'name': 'Radish', 'variety': 'French Breakfast', 'plant_type': 'vegetable', 'description': 'Elongated red radish with white tip. Milder and less peppery than Cherry Belle.', 'days_to_maturity_min': 25, 'days_to_maturity_max': 30, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 1, 'seed_depth_inches': 0.50, 'min_temp_f': 25, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': -4, 'growing_tips': 'Great with butter and salt (the French way). Slightly slower than Cherry Belle.'},
            {'name': 'Turnip', 'variety': 'Purple Top White Globe', 'plant_type': 'vegetable', 'description': 'Classic turnip with purple top and white bottom. Mild when young.', 'days_to_maturity_min': 50, 'days_to_maturity_max': 60, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 3, 'seed_depth_inches': 0.50, 'min_temp_f': 20, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': -3, 'growing_tips': 'Harvest small (2-3 inches) for mildest flavor. Greens are excellent cooked. Good fall crop.'},
            {'name': 'Parsnip', 'variety': 'Hollow Crown', 'plant_type': 'vegetable', 'description': 'Long, cream-colored root. Nutty, sweet flavor that improves after frost.', 'days_to_maturity_min': 100, 'days_to_maturity_max': 120, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 3, 'seed_depth_inches': 0.50, 'min_temp_f': 10, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': -3, 'growing_tips': 'Very slow to germinate (2-4 weeks). Use fresh seed only. Leave in ground through frost for sweetest flavor.'},
            {'name': 'Rutabaga', 'variety': 'American Purple Top', 'plant_type': 'vegetable', 'description': 'Large root vegetable, cross between turnip and cabbage. Sweet, earthy flavor.', 'days_to_maturity_min': 85, 'days_to_maturity_max': 95, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 4, 'seed_depth_inches': 0.50, 'min_temp_f': 15, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': -3, 'growing_tips': 'Best as fall crop — sow in mid-summer. Sweeter than turnips after frost. Stores very well.'},
            # ONION FAMILY
            {'name': 'Onion', 'variety': 'Yellow Sweet Spanish', 'plant_type': 'vegetable', 'description': 'Large, mild yellow onion. Great for cooking. Long-day type suited for NJ.', 'days_to_maturity_min': 100, 'days_to_maturity_max': 115, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 4, 'seed_depth_inches': 0.25, 'min_temp_f': 20, 'start_indoors': True, 'weeks_start_indoors': 10, 'weeks_transplant': -3, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'NJ needs long-day onion varieties. Start very early indoors or buy sets. Stop watering when tops fall over.'},
            {'name': 'Leek', 'variety': 'American Flag', 'plant_type': 'vegetable', 'description': 'Mild, sweet onion cousin. Thick white stalks. Hardy through NJ winters.', 'days_to_maturity_min': 100, 'days_to_maturity_max': 120, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 3, 'seed_depth_inches': 0.12, 'min_temp_f': 10, 'start_indoors': True, 'weeks_start_indoors': 10, 'weeks_transplant': -3, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'Plant in a trench and hill soil around the stalk as it grows. Very slow growing.'},
            # CELERY
            {'name': 'Celery', 'variety': 'Utah Tall', 'plant_type': 'vegetable', 'description': 'Classic green celery. Crisp stalks, long growing season required.', 'days_to_maturity_min': 100, 'days_to_maturity_max': 120, 'sun_requirement': 'full_sun', 'water_needs': 'high', 'spacing_inches': 6, 'seed_depth_inches': 0.12, 'min_temp_f': 30, 'start_indoors': True, 'weeks_start_indoors': 10, 'weeks_transplant': 0, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'One of the hardest vegetables to grow. Needs constant moisture, rich soil, and cool temps.'},
            # CORN
            {'name': 'Sweet Corn', 'variety': 'Silver Queen', 'plant_type': 'vegetable', 'description': 'Classic white sweet corn. Large ears, excellent flavor. Late season.', 'days_to_maturity_min': 88, 'days_to_maturity_max': 92, 'sun_requirement': 'full_sun', 'water_needs': 'high', 'spacing_inches': 12, 'seed_depth_inches': 1.0, 'min_temp_f': 50, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': 1, 'growing_tips': 'Plant in blocks (not rows) for pollination — at least 4 rows. A NJ summer staple.'},
            {'name': 'Sweet Corn', 'variety': 'Peaches and Cream', 'plant_type': 'vegetable', 'description': 'Bicolor sweet corn with mixed yellow and white kernels. Sweet and tender.', 'days_to_maturity_min': 70, 'days_to_maturity_max': 83, 'sun_requirement': 'full_sun', 'water_needs': 'high', 'spacing_inches': 12, 'seed_depth_inches': 1.0, 'min_temp_f': 50, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': 1, 'growing_tips': 'Earlier than Silver Queen. Plant in blocks. Eat immediately after picking — sugar turns to starch fast.'},
            # POTATOES
            {'name': 'Potato', 'variety': 'Yukon Gold', 'plant_type': 'vegetable', 'description': 'Yellow-fleshed, buttery potato. Great all-purpose — bake, mash, roast.', 'days_to_maturity_min': 70, 'days_to_maturity_max': 90, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 12, 'seed_depth_inches': 4.0, 'min_temp_f': 28, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': -2, 'growing_tips': 'Plant seed potatoes (not grocery store). Hill soil around stems as they grow. Harvest after tops die back.'},
            {'name': 'Sweet Potato', 'variety': 'Beauregard', 'plant_type': 'vegetable', 'description': 'Orange sweet potato with reddish skin. Sweet, moist flesh. Very productive.', 'days_to_maturity_min': 90, 'days_to_maturity_max': 100, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 12, 'seed_depth_inches': None, 'min_temp_f': 60, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 3, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'Planted from slips (sprouted shoots), not seeds. Needs warm soil. Cure after harvest in a warm spot.'},
            # OKRA
            {'name': 'Okra', 'variety': 'Clemson Spineless', 'plant_type': 'vegetable', 'description': 'Classic okra variety. Tender, spineless pods. Productive in hot weather.', 'days_to_maturity_min': 55, 'days_to_maturity_max': 65, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 24, 'seed_depth_inches': 0.75, 'min_temp_f': 55, 'start_indoors': True, 'weeks_start_indoors': 3, 'weeks_transplant': 2, 'can_direct_sow': True, 'weeks_direct_sow': 2, 'growing_tips': 'Loves heat — the hotter the better. Harvest pods at 2-3 inches. Soak seeds overnight before planting.'},
            # HERBS
            {'name': 'Basil', 'variety': 'Genovese', 'plant_type': 'herb', 'description': 'Classic Italian sweet basil. Essential for pesto, caprese, and pasta.', 'days_to_maturity_min': 60, 'days_to_maturity_max': 70, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 12, 'seed_depth_inches': 0.25, 'min_temp_f': 50, 'start_indoors': True, 'weeks_start_indoors': 6, 'weeks_transplant': 2, 'can_direct_sow': True, 'weeks_direct_sow': 2, 'growing_tips': 'Pinch flowers to keep producing leaves. Very frost sensitive. Pairs great with tomatoes.'},
            {'name': 'Basil', 'variety': 'Thai', 'plant_type': 'herb', 'description': 'Purple-stemmed basil with spicy, anise-like flavor. Essential for Thai cooking.', 'days_to_maturity_min': 60, 'days_to_maturity_max': 70, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 12, 'seed_depth_inches': 0.25, 'min_temp_f': 50, 'start_indoors': True, 'weeks_start_indoors': 6, 'weeks_transplant': 2, 'can_direct_sow': True, 'weeks_direct_sow': 2, 'growing_tips': 'More heat tolerant than Genovese. Beautiful purple flowers. Holds flavor better when cooked.'},
            {'name': 'Cilantro', 'variety': 'Santo (Slow Bolt)', 'plant_type': 'herb', 'description': 'Slow-bolting cilantro. Fresh leaves for salsa, seeds (coriander) for spice.', 'days_to_maturity_min': 50, 'days_to_maturity_max': 55, 'sun_requirement': 'partial_sun', 'water_needs': 'moderate', 'spacing_inches': 6, 'seed_depth_inches': 0.25, 'min_temp_f': 25, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': -2, 'growing_tips': 'Bolts quickly in heat. Succession sow every 3 weeks. Let some bolt for free coriander seeds.'},
            {'name': 'Parsley', 'variety': 'Italian Flat Leaf', 'plant_type': 'herb', 'description': 'Flat-leaf parsley with strong flavor. More flavorful than curly types.', 'days_to_maturity_min': 70, 'days_to_maturity_max': 80, 'sun_requirement': 'partial_sun', 'water_needs': 'moderate', 'spacing_inches': 6, 'seed_depth_inches': 0.25, 'min_temp_f': 20, 'start_indoors': True, 'weeks_start_indoors': 8, 'weeks_transplant': -2, 'can_direct_sow': True, 'weeks_direct_sow': -3, 'growing_tips': 'Very slow to germinate (2-4 weeks). Soak seeds overnight to speed it up. Biennial — survives NJ winters.'},
            {'name': 'Dill', 'variety': 'Bouquet', 'plant_type': 'herb', 'description': 'Classic dill with large seed heads. Great for pickles, fish, and salads.', 'days_to_maturity_min': 50, 'days_to_maturity_max': 60, 'sun_requirement': 'full_sun', 'water_needs': 'low', 'spacing_inches': 8, 'seed_depth_inches': 0.25, 'min_temp_f': 25, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': -2, 'growing_tips': 'Self-seeds aggressively. Attracts beneficial insects.'},
            {'name': 'Mint', 'variety': 'Spearmint', 'plant_type': 'herb', 'description': 'Classic spearmint. Refreshing for drinks, tea, and cooking.', 'days_to_maturity_min': 60, 'days_to_maturity_max': 90, 'sun_requirement': 'partial_shade', 'water_needs': 'high', 'spacing_inches': 18, 'seed_depth_inches': 0.12, 'min_temp_f': 0, 'start_indoors': True, 'weeks_start_indoors': 8, 'weeks_transplant': -2, 'can_direct_sow': True, 'weeks_direct_sow': -2, 'growing_tips': 'WARNING: Extremely invasive. Always plant in a container or it will take over your garden. Seriously.'},
            {'name': 'Rosemary', 'variety': 'Common', 'plant_type': 'herb', 'description': 'Woody, aromatic Mediterranean herb. Essential for roasted meats and potatoes.', 'days_to_maturity_min': 80, 'days_to_maturity_max': 120, 'sun_requirement': 'full_sun', 'water_needs': 'low', 'spacing_inches': 24, 'seed_depth_inches': 0.25, 'min_temp_f': 15, 'start_indoors': True, 'weeks_start_indoors': 10, 'weeks_transplant': 2, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'Very slow from seed — buy transplants. Perennial in Zone 7+. Bring inside in cold winters.'},
            {'name': 'Thyme', 'variety': 'Common English', 'plant_type': 'herb', 'description': 'Low-growing perennial herb. Earthy, slightly minty flavor.', 'days_to_maturity_min': 85, 'days_to_maturity_max': 95, 'sun_requirement': 'full_sun', 'water_needs': 'low', 'spacing_inches': 12, 'seed_depth_inches': 0.12, 'min_temp_f': 0, 'start_indoors': True, 'weeks_start_indoors': 8, 'weeks_transplant': 0, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'Perennial — plant once, harvest for years. Prefers lean, well-drained soil. Prune after flowering.'},
            {'name': 'Chives', 'variety': 'Common', 'plant_type': 'herb', 'description': 'Mild onion-flavored herb. Pretty purple flowers that are also edible.', 'days_to_maturity_min': 60, 'days_to_maturity_max': 90, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 8, 'seed_depth_inches': 0.25, 'min_temp_f': -20, 'start_indoors': True, 'weeks_start_indoors': 8, 'weeks_transplant': -2, 'can_direct_sow': True, 'weeks_direct_sow': -2, 'growing_tips': 'Extremely cold hardy perennial. One of the first things up in spring. Divide clumps every 2-3 years.'},
            # FLOWERS
            {'name': 'Marigold', 'variety': 'French Dwarf', 'plant_type': 'flower', 'description': 'Compact, colorful annual. Natural pest deterrent — great companion plant.', 'days_to_maturity_min': 50, 'days_to_maturity_max': 60, 'sun_requirement': 'full_sun', 'water_needs': 'low', 'spacing_inches': 8, 'seed_depth_inches': 0.25, 'min_temp_f': 40, 'start_indoors': True, 'weeks_start_indoors': 6, 'weeks_transplant': 1, 'can_direct_sow': True, 'weeks_direct_sow': 1, 'growing_tips': 'Deadhead spent blooms for continuous flowering. Plant around vegetables to deter aphids and nematodes.'},
            {'name': 'Sunflower', 'variety': 'Mammoth', 'plant_type': 'flower', 'description': 'Giant sunflower reaching 10-12 feet. Big seed heads for birds or snacking.', 'days_to_maturity_min': 80, 'days_to_maturity_max': 100, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 24, 'seed_depth_inches': 1.0, 'min_temp_f': 40, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': 0, 'growing_tips': 'Direct sow after last frost. Stake when tall. Attracts pollinators all season.'},
            {'name': 'Nasturtium', 'variety': 'Jewel Mix', 'plant_type': 'flower', 'description': 'Edible flowers in red, orange, and yellow. Peppery flavor. Trails beautifully.', 'days_to_maturity_min': 55, 'days_to_maturity_max': 65, 'sun_requirement': 'full_sun', 'water_needs': 'low', 'spacing_inches': 12, 'seed_depth_inches': 0.50, 'min_temp_f': 40, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': 0, 'growing_tips': 'Trap crop for aphids — plant near veggies to lure pests away. Thrives in poor soil. Flowers and leaves are edible.'},
            {'name': 'Zinnia', 'variety': 'Giant Dahlia Mix', 'plant_type': 'flower', 'description': 'Large, colorful double blooms. Excellent cut flower. Attracts butterflies.', 'days_to_maturity_min': 75, 'days_to_maturity_max': 90, 'sun_requirement': 'full_sun', 'water_needs': 'low', 'spacing_inches': 12, 'seed_depth_inches': 0.25, 'min_temp_f': 40, 'start_indoors': True, 'weeks_start_indoors': 4, 'weeks_transplant': 1, 'can_direct_sow': True, 'weeks_direct_sow': 1, 'growing_tips': 'Cut-and-come-again — the more you cut, the more they bloom. Great pollinator attractor.'},
                        # LEAFY GREENS (additions)
            {'name': 'Arugula', 'variety': 'Astro', 'plant_type': 'vegetable', 'description': 'Peppery Italian salad green. Fast-growing, cool-season. Bolts quickly in heat.', 'days_to_maturity_min': 30, 'days_to_maturity_max': 40, 'sun_requirement': 'partial_sun', 'water_needs': 'moderate', 'spacing_inches': 4, 'seed_depth_inches': 0.25, 'min_temp_f': 25, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': -4, 'growing_tips': 'One of the fastest greens you can grow. Succession sow every 2 weeks. Flavor gets spicy in heat.'},
            {'name': 'Bok Choy', 'variety': 'Toy Choi', 'plant_type': 'vegetable', 'description': 'Compact Asian cabbage with crisp white stalks and tender green leaves.', 'days_to_maturity_min': 30, 'days_to_maturity_max': 45, 'sun_requirement': 'partial_sun', 'water_needs': 'moderate', 'spacing_inches': 6, 'seed_depth_inches': 0.25, 'min_temp_f': 25, 'start_indoors': True, 'weeks_start_indoors': 4, 'weeks_transplant': -2, 'can_direct_sow': True, 'weeks_direct_sow': -3, 'growing_tips': 'Bolts fast in heat — best as spring or fall crop. Harvest whole heads or take outer leaves.'},
            {'name': 'Mustard Greens', 'variety': 'Southern Giant Curled', 'plant_type': 'vegetable', 'description': 'Large frilly leaves with a spicy, horseradish-like kick. Southern staple.', 'days_to_maturity_min': 35, 'days_to_maturity_max': 45, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 6, 'seed_depth_inches': 0.25, 'min_temp_f': 20, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': -3, 'growing_tips': 'Milder when young, spicier as it matures. Great cooked like collards.'},
 
            # ALLIUMS (additions)
            {'name': 'Garlic', 'variety': 'Music (Hardneck)', 'plant_type': 'vegetable', 'description': 'Hardneck garlic with large, easy-to-peel cloves. Bold, spicy flavor. Produces scapes.', 'days_to_maturity_min': 240, 'days_to_maturity_max': 270, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 6, 'seed_depth_inches': 2.0, 'min_temp_f': 0, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': 26, 'growing_tips': 'Plant cloves in fall (Oct–Nov) for harvest the following July. Harvest scapes in June for a bonus crop.'},
 
            # PERENNIALS (vegetables)
            {'name': 'Asparagus', 'variety': 'Jersey Knight', 'plant_type': 'vegetable', 'description': 'All-male hybrid with thick, tender spears. Productive perennial — harvest for 15+ years.', 'days_to_maturity_min': 730, 'days_to_maturity_max': 1095, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 18, 'seed_depth_inches': 6.0, 'min_temp_f': -20, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': -3, 'growing_tips': 'Plant crowns in early spring. Do not harvest first 2 years — let plants establish. After year 3, harvest 6-8 weeks each spring.'},
            {'name': 'Rhubarb', 'variety': 'Victoria', 'plant_type': 'vegetable', 'description': 'Classic tart red-green stalks. Perennial — comes back every year. Leaves are toxic, stalks only.', 'days_to_maturity_min': 365, 'days_to_maturity_max': 730, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 36, 'seed_depth_inches': 2.0, 'min_temp_f': -20, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': -4, 'growing_tips': 'Plant crowns in early spring. Never eat the leaves (oxalic acid). Do not harvest year 1. Divide every 5-8 years.'},
 
            # PEPPERS (additions)
            {'name': 'Pepper', 'variety': 'Cayenne', 'plant_type': 'vegetable', 'description': 'Long, thin hot pepper. Drying classic. 30,000-50,000 Scoville units.', 'days_to_maturity_min': 70, 'days_to_maturity_max': 80, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 18, 'seed_depth_inches': 0.25, 'min_temp_f': 55, 'start_indoors': True, 'weeks_start_indoors': 8, 'weeks_transplant': 2, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'Let peppers turn red on the plant for max heat. Thread on a string to air-dry for cayenne powder.'},
            {'name': 'Pepper', 'variety': 'Poblano', 'plant_type': 'vegetable', 'description': 'Mild-to-medium chile. Perfect for chile rellenos. Dried, they become anchos.', 'days_to_maturity_min': 65, 'days_to_maturity_max': 80, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 18, 'seed_depth_inches': 0.25, 'min_temp_f': 55, 'start_indoors': True, 'weeks_start_indoors': 8, 'weeks_transplant': 2, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'Heat varies plant-to-plant. Harvest green for stuffing, red-ripe for sweeter flavor or to dry into anchos.'},
 
            # FRUIT
            {'name': 'Strawberry', 'variety': 'Jewel (June-bearing)', 'plant_type': 'fruit', 'description': 'Large, sweet berries. One big harvest in June. Developed at Cornell, well-suited to NJ.', 'days_to_maturity_min': 365, 'days_to_maturity_max': 400, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 18, 'seed_depth_inches': None, 'min_temp_f': -20, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'Plant bare-root crowns in early spring. Pinch first-year blossoms so plants establish. Peak production years 2-3.'},
            {'name': 'Blueberry', 'variety': 'Bluecrop', 'plant_type': 'fruit', 'description': 'Classic Northern Highbush blueberry. Large berries, heavy yields. NJ state fruit origin.', 'days_to_maturity_min': 730, 'days_to_maturity_max': 1095, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 60, 'seed_depth_inches': None, 'min_temp_f': -20, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'Needs acidic soil (pH 4.5-5.5). Plant 2+ varieties for cross-pollination. First real harvest in year 3.'},
            {'name': 'Raspberry', 'variety': 'Heritage (Ever-bearing)', 'plant_type': 'fruit', 'description': 'Red raspberries on fall-bearing canes. Two harvests possible. Very productive.', 'days_to_maturity_min': 365, 'days_to_maturity_max': 730, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 30, 'seed_depth_inches': None, 'min_temp_f': -20, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'Cut all canes to the ground in late winter for one big fall crop, or leave some for a smaller summer harvest. Runners spread — give them space.'},
            {'name': 'Blackberry', 'variety': 'Triple Crown (Thornless)', 'plant_type': 'fruit', 'description': 'Thornless semi-erect blackberry. Large sweet berries. Disease resistant.', 'days_to_maturity_min': 365, 'days_to_maturity_max': 730, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 48, 'seed_depth_inches': None, 'min_temp_f': -10, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'Fruits on second-year canes. After harvest, cut fruited canes to ground. Trellis for easier picking.'},
 
            # HERBS (additions)
            {'name': 'Sage', 'variety': 'Common Garden', 'plant_type': 'herb', 'description': 'Classic culinary sage. Silver-green leaves. Essential for poultry seasoning and brown-butter sauces.', 'days_to_maturity_min': 75, 'days_to_maturity_max': 90, 'sun_requirement': 'full_sun', 'water_needs': 'low', 'spacing_inches': 18, 'seed_depth_inches': 0.25, 'min_temp_f': -20, 'start_indoors': True, 'weeks_start_indoors': 8, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': 0, 'growing_tips': 'Perennial — survives NJ winters. Harvest leaves before flowering for best flavor. Replace plants every 3-4 years.'},
            {'name': 'Oregano', 'variety': 'Greek', 'plant_type': 'herb', 'description': 'True oregano with strong, pungent flavor. Perennial. Essential for Italian and Greek cooking.', 'days_to_maturity_min': 75, 'days_to_maturity_max': 90, 'sun_requirement': 'full_sun', 'water_needs': 'low', 'spacing_inches': 12, 'seed_depth_inches': 0.12, 'min_temp_f': -10, 'start_indoors': True, 'weeks_start_indoors': 8, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': 1, 'growing_tips': 'Flavor is strongest just before flowering. Dries beautifully. Spreads — consider containing with a bed edge.'},
            {'name': 'Lavender', 'variety': 'Munstead (English)', 'plant_type': 'herb', 'description': 'Hardy English lavender with purple flowers and classic fragrance. Culinary and ornamental.', 'days_to_maturity_min': 90, 'days_to_maturity_max': 120, 'sun_requirement': 'full_sun', 'water_needs': 'low', 'spacing_inches': 24, 'seed_depth_inches': 0.12, 'min_temp_f': -20, 'start_indoors': True, 'weeks_start_indoors': 10, 'weeks_transplant': 2, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'Needs well-drained soil — dies in wet roots. Prune after flowering to keep shape. Slow to establish from seed; buy plants if you can.'},
            {'name': 'Tarragon', 'variety': 'French', 'plant_type': 'herb', 'description': 'Fine-textured herb with anise-like flavor. Essential for béarnaise and chicken dishes.', 'days_to_maturity_min': 75, 'days_to_maturity_max': 90, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 24, 'seed_depth_inches': None, 'min_temp_f': -20, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'French tarragon only grows from cuttings/divisions, NOT seeds (seed packets are usually Russian tarragon — flavorless). Buy a plant.'},
            {'name': 'Lemon Balm', 'variety': 'Common', 'plant_type': 'herb', 'description': 'Minty lemon-scented herb. Great in teas and cocktails. Shade tolerant.', 'days_to_maturity_min': 70, 'days_to_maturity_max': 80, 'sun_requirement': 'partial_shade', 'water_needs': 'moderate', 'spacing_inches': 18, 'seed_depth_inches': 0.12, 'min_temp_f': -20, 'start_indoors': True, 'weeks_start_indoors': 8, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': 0, 'growing_tips': 'Perennial mint-family herb — spreads aggressively. Grow in containers or commit to an area. Pinch flowers for more leaves.'},
 
            # FLOWERS (additions)
            {'name': 'Cosmos', 'variety': 'Sensation Mix', 'plant_type': 'flower', 'description': 'Tall daisy-like flowers in pink, white, and crimson. Pollinator magnet.', 'days_to_maturity_min': 70, 'days_to_maturity_max': 85, 'sun_requirement': 'full_sun', 'water_needs': 'low', 'spacing_inches': 12, 'seed_depth_inches': 0.25, 'min_temp_f': 40, 'start_indoors': False, 'weeks_start_indoors': None, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': 0, 'growing_tips': 'Tolerates poor soil — rich soil gives lots of foliage but few blooms. Reseeds itself freely.'},
            {'name': 'Calendula', 'variety': 'Pacific Beauty', 'plant_type': 'flower', 'description': 'Pot marigold with edible petals. Orange and yellow flowers. Different from true marigolds.', 'days_to_maturity_min': 50, 'days_to_maturity_max': 60, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 8, 'seed_depth_inches': 0.50, 'min_temp_f': 25, 'start_indoors': True, 'weeks_start_indoors': 6, 'weeks_transplant': -2, 'can_direct_sow': True, 'weeks_direct_sow': -3, 'growing_tips': 'Petals are edible and peppery — great in salads. Deadhead for more blooms. Prefers cool weather.'},
            {'name': 'Black-Eyed Susan', 'variety': 'Goldsturm', 'plant_type': 'flower', 'description': 'Classic golden-yellow daisy with dark center. Perennial — comes back every year.', 'days_to_maturity_min': 100, 'days_to_maturity_max': 120, 'sun_requirement': 'full_sun', 'water_needs': 'low', 'spacing_inches': 18, 'seed_depth_inches': 0.12, 'min_temp_f': -20, 'start_indoors': True, 'weeks_start_indoors': 10, 'weeks_transplant': 0, 'can_direct_sow': True, 'weeks_direct_sow': -4, 'growing_tips': 'Native wildflower. Very drought tolerant once established. Attracts finches in late summer.'},
            {'name': 'Bee Balm', 'variety': 'Jacob Cline', 'plant_type': 'flower', 'description': 'Scarlet-red perennial that hummingbirds love. Mint-family, fragrant leaves.', 'days_to_maturity_min': 120, 'days_to_maturity_max': 150, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 24, 'seed_depth_inches': 0.12, 'min_temp_f': -20, 'start_indoors': True, 'weeks_start_indoors': 10, 'weeks_transplant': 0, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'Hummingbird and bee magnet. Leaves make Earl Grey-like tea. Mildew prone — space generously for airflow.'},
 
            # MISC VEGETABLE ADDITIONS
            {'name': 'Fennel', 'variety': 'Florence (Bulbing)', 'plant_type': 'vegetable', 'description': 'Bulbing fennel with anise-like flavor. Swollen leaf bases eaten raw or roasted.', 'days_to_maturity_min': 80, 'days_to_maturity_max': 100, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 8, 'seed_depth_inches': 0.25, 'min_temp_f': 25, 'start_indoors': True, 'weeks_start_indoors': 6, 'weeks_transplant': -2, 'can_direct_sow': True, 'weeks_direct_sow': -2, 'growing_tips': 'Best as a fall crop — bolts in summer heat. Mound soil around bulbs as they develop for tender white bases.'},
            {'name': 'Pepper', 'variety': 'Bell (Green)', 'plant_type': 'vegetable', 'description': 'Standard green bell pepper. Crisp, slightly bitter. Turns red, yellow, or orange if left to ripen.', 'days_to_maturity_min': 65, 'days_to_maturity_max': 75, 'sun_requirement': 'full_sun', 'water_needs': 'moderate', 'spacing_inches': 18, 'seed_depth_inches': 0.25, 'min_temp_f': 55, 'start_indoors': True, 'weeks_start_indoors': 8, 'weeks_transplant': 2, 'can_direct_sow': False, 'weeks_direct_sow': None, 'growing_tips': 'Green peppers are just unripe bells — leave on the plant longer for red/yellow. Support heavily-fruited plants.'},
        ]
        created = 0
        for plant_data in plants:
            _, was_created = Plant.objects.update_or_create(
                name=plant_data['name'],
                variety=plant_data.get('variety', ''),
                defaults=plant_data,
            )
            if was_created:
                created += 1
        self.stdout.write(f'  Plants: {created} created, {len(plants) - created} updated')

    def load_companions(self):
        def get_plant(name, variety=''):
            try:
                if variety:
                    return Plant.objects.get(name=name, variety=variety)
                return Plant.objects.filter(name=name).first()
            except Plant.DoesNotExist:
                return Plant.objects.filter(name=name).first()

        relationships = [
            ('Tomato', '', 'Basil', 'Genovese', 'companion', 'Basil repels aphids, hornworms, and whiteflies. May improve tomato flavor.'),
            ('Tomato', '', 'Marigold', 'French Dwarf', 'companion', 'Marigolds repel root-knot nematodes and whiteflies from tomatoes.'),
            ('Tomato', '', 'Carrot', 'Nantes', 'companion', 'Carrots loosen soil around tomato roots. Tomatoes provide light shade.'),
            ('Tomato', '', 'Parsley', 'Italian Flat Leaf', 'companion', 'Parsley attracts hoverflies and parasitic wasps that prey on hornworms.'),
            ('Tomato', '', 'Nasturtium', 'Jewel Mix', 'companion', 'Nasturtiums are a trap crop — aphids prefer them over tomatoes.'),
            ('Tomato', '', 'Chives', 'Common', 'companion', 'Chives deter aphids and may help prevent fungal diseases.'),
            ('Tomato', '', 'Cabbage', 'Golden Acre', 'antagonist', 'Tomatoes can stunt brassica growth. Keep them separate.'),
            ('Tomato', '', 'Sweet Corn', 'Silver Queen', 'antagonist', 'Both are heavy feeders and attract corn earworm/tomato fruitworm.'),
            ('Pepper', '', 'Basil', 'Genovese', 'companion', 'Basil repels aphids and spider mites from peppers.'),
            ('Pepper', '', 'Cilantro', 'Santo (Slow Bolt)', 'companion', 'Cilantro attracts beneficial insects and provides ground cover.'),
            ('Pepper', '', 'Marigold', 'French Dwarf', 'companion', 'Marigolds deter many pepper pests including aphids.'),
            ('Cucumber', '', 'Dill', 'Bouquet', 'companion', 'Dill attracts beneficial wasps that prey on cucumber pests. Classic pickle combo.'),
            ('Cucumber', '', 'Nasturtium', 'Jewel Mix', 'companion', 'Nasturtiums repel cucumber beetles and aphids.'),
            ('Cucumber', '', 'Sunflower', 'Mammoth', 'companion', 'Sunflowers attract pollinators and provide afternoon shade.'),
            ('Cucumber', '', 'Radish', 'Cherry Belle', 'companion', 'Radishes deter cucumber beetles. Plant as a border.'),
            ('Zucchini', '', 'Marigold', 'French Dwarf', 'companion', 'Marigolds attract pollinators and deter squash bugs.'),
            ('Zucchini', '', 'Nasturtium', 'Jewel Mix', 'companion', 'Nasturtiums repel squash bugs and vine borers.'),
            ('Watermelon', '', 'Marigold', 'French Dwarf', 'companion', 'Marigolds attract pollinators needed for fruit set.'),
            ('Watermelon', '', 'Sunflower', 'Mammoth', 'companion', 'Sunflowers attract pollinators and act as a windbreak.'),
            ('Green Bean', '', 'Sweet Corn', 'Silver Queen', 'companion', 'Three Sisters — beans fix nitrogen, corn provides a trellis.'),
            ('Green Bean', '', 'Zucchini', 'Black Beauty', 'companion', 'Three Sisters — squash shades soil, beans fix nitrogen.'),
            ('Green Bean', '', 'Carrot', 'Nantes', 'companion', 'Beans fix nitrogen that benefits carrots. Good use of space.'),
            ('Green Bean', '', 'Cucumber', '', 'companion', 'Both benefit from similar conditions. Beans add nitrogen.'),
            ('Green Bean', '', 'Onion', 'Yellow Sweet Spanish', 'antagonist', 'Alliums can stunt bean growth.'),
            ('Lettuce', '', 'Radish', 'Cherry Belle', 'companion', 'Radishes mature fast, freeing space before lettuce heads up.'),
            ('Lettuce', '', 'Carrot', 'Nantes', 'companion', 'Lettuce shades soil keeping carrots cool.'),
            ('Lettuce', '', 'Chives', 'Common', 'companion', 'Chives deter aphids which are a common lettuce pest.'),
            ('Carrot', '', 'Onion', 'Yellow Sweet Spanish', 'companion', 'Onion scent masks carrots from carrot rust fly.'),
            ('Carrot', '', 'Leek', 'American Flag', 'companion', 'Leeks repel carrot fly, carrots repel leek moth. Mutual benefit.'),
            ('Carrot', '', 'Rosemary', 'Common', 'companion', 'Rosemary repels carrot fly with its strong scent.'),
            ('Carrot', '', 'Dill', 'Bouquet', 'antagonist', 'Dill can cross-pollinate with carrots (same family) and inhibit growth.'),
            ('Broccoli', '', 'Nasturtium', 'Jewel Mix', 'companion', 'Nasturtiums trap aphids away from broccoli.'),
            ('Broccoli', '', 'Dill', 'Bouquet', 'companion', 'Dill attracts beneficial wasps that parasitize cabbage worms.'),
            ('Cabbage', '', 'Mint', 'Spearmint', 'companion', 'Mint deters cabbage moths. Plant mint in containers nearby!'),
            ('Cabbage', '', 'Thyme', 'Common English', 'companion', 'Thyme deters cabbage worms with its strong scent.'),
            ('Sweet Corn', '', 'Pumpkin', 'Sugar Pie', 'companion', 'Three Sisters — pumpkin leaves shade ground and retain moisture.'),
            ('Dill', 'Bouquet', 'Lettuce', '', 'companion', 'Dill attracts beneficial insects that protect lettuce.'),
            ('Rosemary', 'Common', 'Cabbage', 'Golden Acre', 'companion', 'Rosemary repels cabbage moths and brassica pests.'),
            ('Thyme', 'Common English', 'Eggplant', 'Black Beauty', 'companion', 'Thyme deters garden moths and attracts beneficial insects.'),
            ('Zinnia', '', 'Zucchini', '', 'companion', 'Zinnias attract pollinators that squash needs for fruit set.'),
            ('Zinnia', '', 'Tomato', '', 'companion', 'Zinnias attract ladybugs that eat tomato pests.'),
            ('Nasturtium', '', 'Cabbage', '', 'companion', 'Nasturtiums trap aphids and cabbage moths away from brassicas.'),
            
            # Garlic — aphid-repelling 
            ('Garlic', 'Music (Hardneck)', 'Tomato', '', 'companion', 'Garlic repels aphids, spider mites, and Japanese beetles from tomatoes.'),
            ('Garlic', 'Music (Hardneck)', 'Strawberry', 'Jewel (June-bearing)', 'companion', 'Garlic deters spider mites and improves flavor of strawberries.'),
            ('Garlic', 'Music (Hardneck)', 'Carrot', 'Nantes', 'companion', 'Garlic scent confuses carrot rust flies.'),
            ('Garlic', 'Music (Hardneck)', 'Green Bean', 'Blue Lake (Bush)', 'antagonist', 'Alliums stunt bean and pea growth.'),
 
            # Strawberry pairings
            ('Strawberry', 'Jewel (June-bearing)', 'Spinach', 'Bloomsdale Long Standing', 'companion', 'Spinach provides ground cover and deters some strawberry pests.'),
            ('Strawberry', 'Jewel (June-bearing)', 'Cabbage', 'Golden Acre', 'antagonist', 'Brassicas and strawberries compete for nutrients and attract similar pests.'),
 
            # Asparagus pairings
            ('Asparagus', 'Jersey Knight', 'Tomato', '', 'companion', 'Classic pairing — asparagus repels root nematodes, tomatoes repel asparagus beetle.'),
            ('Asparagus', 'Jersey Knight', 'Parsley', 'Italian Flat Leaf', 'companion', 'Parsley strengthens asparagus flavor and attracts beneficial insects.'),
            ('Asparagus', 'Jersey Knight', 'Basil', 'Genovese', 'companion', 'Basil repels asparagus beetles.'),
 
            # Herb synergies
            ('Sage', 'Common Garden', 'Cabbage', 'Golden Acre', 'companion', 'Sage repels cabbage moths with its strong scent.'),
            ('Sage', 'Common Garden', 'Carrot', 'Nantes', 'companion', 'Sage deters carrot fly.'),
            ('Sage', 'Common Garden', 'Cucumber', '', 'antagonist', 'Sage can inhibit cucumber growth.'),
            ('Oregano', 'Greek', 'Pepper', '', 'companion', 'Oregano repels aphids from peppers.'),
            ('Oregano', 'Greek', 'Broccoli', 'Calabrese', 'companion', 'Oregano provides ground cover and attracts beneficial pollinators.'),
            ('Lavender', 'Munstead (English)', 'Tomato', '', 'companion', 'Lavender attracts pollinators and repels moths.'),
            ('Lavender', 'Munstead (English)', 'Cabbage', 'Golden Acre', 'companion', 'Lavender scent deters cabbage moths and aphids.'),
            ('Tarragon', 'French', 'Eggplant', 'Black Beauty', 'companion', 'Tarragon is a general garden benefactor — deters pests and attracts beneficials.'),
            ('Lemon Balm', 'Common', 'Tomato', '', 'companion', 'Lemon balm attracts pollinators and bees to the garden.'),
 
            # Flower pollinator / pest-control pairings
            ('Cosmos', 'Sensation Mix', 'Tomato', '', 'companion', 'Cosmos attract hoverflies and parasitic wasps that prey on tomato pests.'),
            ('Cosmos', 'Sensation Mix', 'Pepper', '', 'companion', 'Cosmos draw pollinators and beneficial insects to peppers.'),
            ('Calendula', 'Pacific Beauty', 'Tomato', '', 'companion', 'Calendula is a trap crop for aphids and attracts beneficial insects.'),
            ('Calendula', 'Pacific Beauty', 'Broccoli', 'Calabrese', 'companion', 'Calendula deters cabbage worms and attracts ladybugs.'),
            ('Bee Balm', 'Jacob Cline', 'Tomato', '', 'companion', 'Bee balm attracts pollinators — may improve tomato flavor and yield.'),
 
            # Arugula / Bok Choy / Mustard Greens
            ('Arugula', 'Astro', 'Carrot', 'Nantes', 'companion', 'Arugula matures fast, freeing space for slower-growing carrots.'),
            ('Bok Choy', 'Toy Choi', 'Nasturtium', 'Jewel Mix', 'companion', 'Nasturtiums trap aphids and flea beetles away from bok choy.'),
            ('Mustard Greens', 'Southern Giant Curled', 'Nasturtium', 'Jewel Mix', 'companion', 'Nasturtiums draw flea beetles away from mustard greens.'),
 
            # Fennel — famously incompatible
            ('Fennel', 'Florence (Bulbing)', 'Tomato', '', 'antagonist', 'Fennel inhibits growth of most garden plants. Give it its own bed.'),
            ('Fennel', 'Florence (Bulbing)', 'Green Bean', 'Blue Lake (Bush)', 'antagonist', 'Fennel secretes compounds that stunt bean growth.'),
 
            # Rhubarb — mostly a loner but a couple notes
            ('Rhubarb', 'Victoria', 'Cabbage', 'Golden Acre', 'companion', 'Rhubarb leaves (toxic) can be used as mulch to deter cabbage worms.'),
            ('Rhubarb', 'Victoria', 'Strawberry', 'Jewel (June-bearing)', 'companion', 'Classic flavor pairing and they grow well near each other.'),
 
            # Blueberry / brambles
            ('Blueberry', 'Bluecrop', 'Strawberry', 'Jewel (June-bearing)', 'companion', 'Both prefer acidic soil — plant together in an acid bed.'),
 
        ]
        created = 0
        for name_a, var_a, name_b, var_b, rel_type, reason in relationships:
            plant_a = get_plant(name_a, var_a)
            plant_b = get_plant(name_b, var_b)
            if not plant_a or not plant_b:
                self.stdout.write(self.style.WARNING(f'  Skipping: {name_a} <-> {name_b} — plant not found'))
                continue
            _, was_created = CompanionRelationship.objects.update_or_create(
                plant_a=plant_a, plant_b=plant_b,
                defaults={'relationship': rel_type, 'reason': reason}
            )
            if was_created:
                created += 1
        self.stdout.write(f'  Companions: {created} created')
