# Generated by Django 6.0.3 on 2026-03-27 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardinessZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(db_index=True, max_length=5, unique=True)),
                ('zone', models.CharField(help_text='e.g. 6a, 6b, 7a', max_length=5)),
                ('avg_last_frost', models.DateField(help_text='Average last spring frost date (use 2000 as base year, e.g. 2000-04-15)')),
                ('avg_first_frost', models.DateField(help_text='Average first fall frost date (use 2000 as base year, e.g. 2000-10-15)')),
            ],
            options={
                'ordering': ['zip_code'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Common name, e.g. 'Tomato'", max_length=100)),
                ('variety', models.CharField(blank=True, help_text="Specific variety, e.g. 'Sun Sugar'", max_length=100)),
                ('plant_type', models.CharField(choices=[('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('herb', 'Herb'), ('flower', 'Flower')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('days_to_maturity_min', models.PositiveIntegerField(help_text='Minimum days from transplant/sow to harvest')),
                ('days_to_maturity_max', models.PositiveIntegerField(help_text='Maximum days from transplant/sow to harvest')),
                ('sun_requirement', models.CharField(choices=[('full_sun', 'Full Sun (6-8+ hrs)'), ('partial_sun', 'Partial Sun (4-6 hrs)'), ('partial_shade', 'Partial Shade (2-4 hrs)'), ('full_shade', 'Full Shade (<2 hrs)')], max_length=20)),
                ('water_needs', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20)),
                ('spacing_inches', models.PositiveIntegerField(help_text='Space between plants in inches')),
                ('seed_depth_inches', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('min_temp_f', models.IntegerField(help_text='Minimum temperature the plant can handle (°F)')),
                ('start_indoors', models.BooleanField(default=False)),
                ('weeks_start_indoors', models.IntegerField(blank=True, help_text='Weeks BEFORE last frost to start indoors (positive number)', null=True)),
                ('weeks_transplant', models.IntegerField(default=0, help_text='Weeks AFTER last frost to transplant outside')),
                ('can_direct_sow', models.BooleanField(default=True)),
                ('weeks_direct_sow', models.IntegerField(blank=True, help_text='Weeks AFTER last frost for direct sow (negative = before)', null=True)),
                ('growing_tips', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name', 'variety'],
                'unique_together': {('name', 'variety')},
            },
        ),
        migrations.CreateModel(
            name='CompanionRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('companion', 'Good Companion'), ('antagonist', 'Antagonist (Keep Apart)')], max_length=20)),
                ('reason', models.TextField(help_text='Why these plants are companions or antagonists')),
                ('plant_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companion_from', to='garden.plant')),
                ('plant_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companion_to', to='garden.plant')),
            ],
            options={
                'ordering': ['plant_a__name', 'plant_b__name'],
                'unique_together': {('plant_a', 'plant_b')},
            },
        ),
    ]
