# Generated by Django 6.0.3 on 2026-03-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrostDateByZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(help_text='e.g. 4a, 6b, 7a', max_length=5, unique=True)),
                ('avg_last_frost', models.DateField(help_text='Average last spring frost (use 2000 as base year, e.g. 2000-04-15)')),
                ('avg_first_frost', models.DateField(help_text='Average first fall frost (use 2000 as base year, e.g. 2000-10-15)')),
            ],
            options={
                'verbose_name': 'Frost Date by Zone',
                'verbose_name_plural': 'Frost Dates by Zone',
                'ordering': ['zone'],
            },
        ),
        migrations.DeleteModel(
            name='HardinessZone',
        ),
    ]
