# Generated by Django 6.0.3 on 2026-04-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_frostdatebyzone_delete_hardinesszone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipToZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(db_index=True, max_length=5, unique=True)),
                ('zone', models.CharField(help_text='e.g. 6b, 7a', max_length=5)),
            ],
            options={
                'verbose_name': 'Zip to Zone',
                'verbose_name_plural': 'Zip to Zone Mappings',
                'ordering': ['zip_code'],
            },
        ),
    ]
